---
- name: kanthaus-nextcloud | setup
  hosts: all
  become: yes
  vars_files:
    - secrets.vars.yml
  vars:
    site: kanthaus-nextcloud
    server_name: cloud.kanthaus.online
    redirects: []
    postgresql_user: kanthaus-nextcloud
    postgresql_database: kanthaus-nextcloud

  tasks:
    - name: Upgrade Nextcloud
      include_role:
        name: nextcloud-upgrade
      vars:
        nextcloud_webroot: "/var/www/{{ site }}/www"