---

- name: install tools
  listen: deploy
  pip:
    name: "{{ item }}"
    virtualenv: "/var/www/{{ site }}/www/env"
  with_items:
    - setuptools
    - pip-tools

- name: pip sync
  listen: deploy
  command: env/bin/pip-sync
  args:
    chdir: "/var/www/{{ site }}/www"

- name: manage.py stuff
  listen: deploy
  command: "env/bin/python manage.py {{ item }}"
  args:
    chdir: "/var/www/{{ site }}/www"
  with_items:
    - check --deploy
    - migrate
    - collectstatic --clear --no-input
    - compilemessages

- name: www ownership
  listen: deploy
  file:
    dest: /var/www/{{ site }}/www
    state: directory
    recurse: yes
    owner: deploy
    group: deploy

- name: restart workers
  listen: restart app
  service:
    name: "{{ site }}-worker.target"
    state: restarted