---

#---------------------------------------------------------
# PHP pool

- name: php fpm pool config
  template:
    src: php.j2
    dest: /etc/php/7.0/fpm/pool.d/{{ site }}.conf
  notify:
    - reload php-fpm


#------------------------------------------------------------------
# nginx config

- name: nginx config
  template:
    src: nginx.j2
    dest: /etc/nginx/sites-available/{{ site }}
  notify:
    - reload nginx

- name: nginx sites-enabled symlink
  file:
    src: /etc/nginx/sites-available/{{ site }}
    dest: /etc/nginx/sites-enabled/{{ site }}
    state: link
  notify:
    - reload nginx

#------------------------------------------------------------------
# initialize basics
# does not actually deploy site, but should be ready to after this

- name: git repo
  git:
    repo: https://github.com/kanthaus/kanthaus.online.git
    dest: /var/www/{{ site }}/www
    update: no
  become: true
  become_user: {{ site }}
