---

- become_user: "{{ site }}-deploy"
  block:

  - name: install tools
    pip:
      name: "{{ item }}"
      virtualenv: "/var/www/{{ site }}/www/env"
    with_items:
      - setuptools
      - pip-tools

  - name: update code
    git:
      repo: https://github.com/yunity/foodsaving-backend.git
      dest: /var/www/{{ site }}/www
      update: yes
      force: yes
      version: "{{ branch }}"

  - name: pip sync
    command: env/bin/pip-sync
    args:
      chdir: "/var/www/{{ site }}/www"
    changed_when: False

  - name: manage.py stuff
    command: "env/bin/python manage.py {{ item }}"
    args:
      chdir: "/var/www/{{ site }}/www"
    with_items:
      - check --deploy
      - migrate
      - collectstatic --clear --no-input
      - compilemessages
      - setup_sparkpost
    changed_when: False

  - name: compile mjml templates
    shell: |
      set -e
      yarn
      ./convert
    args:
      chdir: "/var/www/{{ site }}/www/mjml"
    changed_when: False

    # need to use 'sudo' to allow privileges just for this command
  - name: restart workers
    shell: "sudo systemctl restart {{ site }}-worker.target"
    changed_when: False

  - name: restart huey
    shell: "sudo systemctl restart {{ site }}-huey.service"
    changed_when: False