---

- name: group
  group:
    name: "{{ site }}"
    state: present

- name: user
  user:
    name: "{{ site }}"
    state: present
    group: "{{ site }}"
    createhome: no
    home: "/var/www/{{ site }}"
    shell: /bin/false

- name: directories
  file:
    path: "/var/www/{{ site }}/{{ item }}"
    state: directory
  with_items:
    - www
    - log
    - cert