---

- name: group
  group:
    name: "{{ site }}"
    state: present

- name: user
  user:
    name: "{{ site }}"
    state: present
    group: "{{ site }}"
    createhome: no
    home: "/var/www/{{ site }}"
    shell: /bin/false

- name: set home directory permissions
  file:
    path: "/var/www/{{ site }}"
    owner: "{{ site }}"
    group: "{{ site }}"
    mode: "u=rwx,g=rx,o="

- name: directories
  file:
    path: "/var/www/{{ site }}/{{ item }}"
    state: directory
    owner: "{{ site }}"
    group: "{{ site }}"
    mode: "u=rwx,g=rwx,o="

  with_items:
    - www
    - log
    - cert

- name: generate list of DNS entries
  set_fact:
    dns: "{{ redirects }} + ['{{ server_name }}']"

- name: cert/dns entries
  copy:
    dest: /var/www/{{ site }}/cert/dns
    content: |
      # This file is managed by ansible. It belongs to {{ role_path }}.
      # See https://github.com/yunity/yuca to change.
      {% for entry in dns %}
      {{ entry }}
      {% endfor %}
    backup: true
  notify:
    - generate cert

- name: copy selfsigned cert
  copy:
    dest: /var/www/{{ site }}/cert/{{ item }}
    src: "{{ item }}"
  with_items:
    - fullchain.pem
    - key.pem
  when: we_are_in_vagrant

- name: nginx config
  when: setup_html_vhost is defined
  template:
    src: nginx.j2
    dest: /etc/nginx/sites-available/{{ site }}
  notify:
    - reload nginx

- name: nginx redirect config
  template:
    src: nginx-redirect.j2
    dest: /etc/nginx/sites-available/{{ site }}-redirect
  notify:
    - reload nginx

- name: nginx sites-enabled symlink
  when: setup_html_vhost is defined
  file:
    src: /etc/nginx/sites-available/{{ site }}
    dest: /etc/nginx/sites-enabled/{{ site }}
    state: link
  notify:
    - reload nginx

- name: nginx redirect sites-enabled symlink
  file:
    src: /etc/nginx/sites-available/{{ site }}-redirect
    dest: /etc/nginx/sites-enabled/{{ site }}-redirect
    state: link
  notify:
    - reload nginx

- name: "Adding user 'www-data' to group '{{ site }}'"
  user:
    name: www-data
    groups: "{{ site }}"
    append: yes