---

- name: reload systemd daemon
  systemd:
    daemon_reload: yes

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: reload php-fpm
  service:
    name: php7.0-fpm
    state: reloaded
