---
- name: karrot dev | setup
  hosts: all
  become: yes
  vars_files:
    - secrets.vars.yml
  tasks:

    - name: check ansible version
      include_role:
        name: check-ansible-version

    - name: basic-site
      include_role:
        name: basic-site
      vars:
        site: karrot-dev

    - name: letsencrypt
      include_role:
        name: letsencrypt
      vars:
        site: karrot-dev
        dns:
          - dev.karrot.world
          - dev.foodsaving.world
          - devdev.foodsaving.world
          - karrot-dev.foodsaving.world
          - dev.yunity.org
          - mvp-proposal.yunity.org

    - name: karrot-backend
      include_role:
        name: karrot-backend
      vars:
        site: karrot-dev
        server_name: dev.karrot.world
        redirects:
          - dev.foodsaving.world
          - devdev.foodsaving.world
          - karrot-dev.foodsaving.world
          - dev.yunity.org
          - mvp-proposal.yunity.org
        static_root: /home/deploy/karrot-frontend/master
        from_email_address: karrot.world <noreply@karrot.world>
        redis_db: 4
        influxdb_database: karrot-dev
        postgresql_database: fstool-dev
        postgresql_user: fstool-dev
        workers: 4
        additional_allowed_hosts:
          - .netlify.com
        csrf_trusted_origins:
          - .karrot.world
          - .netlify.com
