---

- name: backup script
  template:
    src: backup.sh.j2
    dest: /var/www/{{ site }}/backup/backup.sh


#------------------------------------------------------------------
# cron jobs

- name: backup cronjob
  cron:
    name: "{{ site }} | backup"
    minute: "0"
    hour: "3"
    job: "cd /var/www/{{ site }}/backup/ && ./backup.sh > /dev/null"
    user: "{{ site }}"
