---

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - python-psycopg2 # needed for ansible postgresql module
    - git
    - virtualenv
    - build-essential # for pip to build some libraries
    - python3
    - python3-dev
    - redis-server
    - gettext

#------------------------------------------------------------------
# database

- name: Start Redis and enable at boot
  service:
    name: redis-server
    enabled: yes
    state: started

- name: Start PostgreSQL and enable at boot
  service:
    name: postgresql
    enabled: yes
    state: started

- postgresql_db:
    name: "{{ postgresql_database }}"
    encoding: UTF-8
    template: template0
  become: true
  become_user: postgres

- postgresql_user:
    db: "{{ postgresql_database }}"
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_password }}"
    priv: ALL
  become: true
  become_user: postgres

#------------------------------------------------------------------
# nginx config

- name: nginx config
  template:
    src: nginx.j2
    dest: /etc/nginx/sites-available/{{ site }}
  notify:
    - reload nginx

- name: nginx sites-enabled symlink
  file:
    src: /etc/nginx/sites-available/{{ site }}
    dest: /etc/nginx/sites-enabled/{{ site }}
    state: link
  notify:
    - reload nginx

- name: create frontend directory
  file:
    path: "{{ static_root }}"
    state: directory
  when: we_are_in_vagrant

- name: dummy frontend file
  copy:
    content: hello
    dest: "{{ static_root }}/index.html"
  when: we_are_in_vagrant

#------------------------------------------------------------------
# initialize basics
# does not actually deploy site, but should be ready to after this

- name: git repo
  git:
    repo: https://github.com/yunity/foodsaving-backend.git
    dest: /var/www/{{ site }}/www
    update: yes
    version: "{{ branch }}"

- name: virtualenv
  command: >
    virtualenv
      --no-setuptools
      --python=python3
      --no-site-packages
      /var/www/{{ site }}/www/env
  args:
    creates: /var/www/{{ site }}/www/env

- name: install tools
  pip:
    name: "{{ item }}"
    virtualenv: "/var/www/{{ site }}/www/env"
  with_items:
    - setuptools
    - pip-tools

- name: pip sync
  command: env/bin/pip-sync
  args:
    chdir: "/var/www/{{ site }}/www"

- name: allow user to restart workers
  copy:
    dest: "/etc/sudoers.d/deploy_{{ site }}"
    content: "%{{ site }} ALL=(ALL) NOPASSWD: /bin/systemctl restart {{ site }}-worker.target\n"

- name: make uploads directory
  file:
    dest: /var/www/{{ site }}/www/{{ uploads_directory }}
    state: directory

#------------------------------------------------------------------
# django settings

- name: django local settings
  template:
    src: local_settings.py.j2
    dest: /var/www/{{ site }}/www/config/local_settings.py
  notify:
    - restart app

#------------------------------------------------------------------
# cron jobs

- name: update pickup dates cronjob
  cron:
    name: "{{ site }} | update pickup dates"
    minute: "0"
    job: "cd /var/www/{{ site }}/www/ && env/bin/python manage.py update_pickup_dates"
    user: "{{ site }}"

- name: process finished pickup dates cronjob
  cron:
    name: "{{ site }} | process finished pickup dates"
    job: "cd /var/www/{{ site }}/www/ && env/bin/python manage.py process_finished_pickup_dates"
    user: "{{ site }}"

- name: send notifications cronjob
  cron:
    name: "{{ site }} | send notifications"
    job: "cd /var/www/{{ site }}/www/ && env/bin/python manage.py send_notifications"
    user: "{{ site }}"

#------------------------------------------------------------------
# systemd servics

- name: systemd daphne service
  template:
    src: systemd.daphne.service.j2
    dest: /etc/systemd/system/{{ site }}-daphne.service
  notify:
    - reload systemd daemon
    - restart daphne

- name: systemd worker target
  template:
    src: systemd.worker.target.j2
    dest: /etc/systemd/system/{{ site }}-worker.target
  notify:
    - reload systemd daemon
    - restart workers

- name: systemd worker service
  template:
    src: systemd.worker.service.j2
    dest: /etc/systemd/system/{{ site }}-worker@.service
  notify:
    - reload systemd daemon
    - restart workers

- name: systemd enable daphne
  systemd:
    name: "{{ site }}-daphne.service"
    state: started
    enabled: yes

- name: systemd enable workers
  systemd:
    name: "{{ site }}-worker.target"
    state: started
    enabled: yes