---
- name: foodsharing Taiwan | setup
  hosts: all
  become: yes
  vars_files:
    - secrets.vars.yml
  vars:
    site: foodsharing-Taiwan
    server_name: app.foodsharing.tw
    redirects:
      - tw.foodsaving.world
      - karrot.foodsharing.tw
  tasks:

    - name: check ansible version
      include_role:
        name: check-ansible-version

    - name: basic-site
      include_role:
        name: basic-site

    - name: karrot-backend
      include_role:
        name: karrot-backend
      vars:
        site_name: Foodsharing Taiwan
        static_root: /home/deploy/karrot-frontend/release
        from_email_address: karrot.world <noreply@karrot.world>
        redis_db: 3
        influxdb_database: fstaiwan
        postgresql_database: fstaiwan
        postgresql_user: fstaiwan
        workers: 4
        csrf_trusted_origins:
          - .foodsharing.tw
