---
- name: foodsharing Taiwan | setup
  hosts: all
  become: yes
  vars_files:
    - secrets.vars.yml
  tasks:

    - name: check ansible version
      include_role:
        name: check-ansible-version

    - name: basic-site
      include_role:
        name: basic-site
      vars:
        site: foodsharing-taiwan

    - name: letsencrypt
      include_role:
        name: letsencrypt
      vars:
        site: foodsharing-taiwan
        dns:
          - app.foodsharing.tw
          - karrot.foodsharing.tw
          - tw.foodsaving.world

    - name: karrot-backend
      include_role:
        name: karrot-backend
      vars:
        site: foodsharing-taiwan
        server_name: app.foodsharing.tw
        redirects:
          - tw.foodsaving.world
          - karrot.foodsharing.tw
        static_root: /home/deploy/karrot-frontend/release
        from_email_address: karrot.world <noreply@karrot.world>
        redis_db: 3
        influxdb_database: fstaiwan
        postgresql_database: fstaiwan
        postgresql_user: fstaiwan
        workers: 4
        csrf_trusted_origins:
          - .foodsharing.tw
