---
- name: kanthaus-online | deploy
  hosts: all
  become: yes
  tasks:

    - name: check ansible version
      include_role:
        name: check-ansible-version

    - name: deploy
      include_role:
        name: grav-deploy
      vars:
        site: kanthaus-online-grav
        branch: master
