---

- name: restart daphne
  listen: restart app
  systemd:
    name: "{{ site }}-daphne.service"
    state: restarted
    daemon_reload: yes

- name: restart workers
  listen: restart app
  systemd:
    name: "{{ site }}-worker.target"
    state: restarted
    daemon_reload: yes
