---

- name: cert/dns entries
  copy:
    dest: /var/www/{{ site }}/cert/dns
    content: |
      {% for entry in dns %}
      {{ entry }}
      {% endfor %}
    backup: true
  notify:
    - generate cert